### ISSUE TITLE
Feil ved minsteinntekt - test i prod

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#154]
Inntektsperioder kommer med desimaler - men takler bare int

```
Failed to fetch subsumsjon. Response message: OK. Error message: Expected an int but was 35520.75 at path $.grunnlagResultat.grunnlagInntektsPerioder[0].inntekt 
```
Stacktrace:

````
no.nav.dagpenger.regel.api.internal.RegelApiSubsumsjonHttpClientException: Failed to fetch subsumsjon. Response message: OK. Error message: Expected an int but was 35520.75 at path $.grunnlagResultat.grunnlagInntektsPerioder[0].inntekt
	at no.nav.dagpenger.regel.api.internal.RegelApiSubsumsjonHttpClient.getSubsumsjon(RegelApiSubsumsjonHttpClient.kt:23)
	at no.nav.dagpenger.regel.api.internal.SynchronousSubsumsjonClient.getSubsumsjonSynchronously(SynchronousSubsumsjonClient.kt:23)
	at no.nav.dagpenger.regel.api.arena.adapter.v1.MinsteinntektOgPeriodeApiKt$MinsteinntektOgPeriodeApi$1$1.invokeSuspend(MinsteinntektOgPeriodeApi.kt:29)
```

**Comment by geiralund** [comment]
Lett å fremprovosere i test - legg til en inntekt med desimaler ^^
