### ISSUE TITLE
feil ved henting av søknadsfakta (AvsluttedeArbeidsforhold)

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#512]
- [x] feil ved henting av søknadsfakta (AvsluttedeArbeidsforhold): Text 'NaN-aN-aN' could not be parsed at index 0
- [x]  feil ved henting av søknadsfakta (AvsluttedeArbeidsforhold): null

**Comment by geiralund** [comment]
feil ved henting av søknadsfakta (AvsluttedeArbeidsforhold): Text 'NaN-aN-aN' could not be parsed at index 0
stacktrace

```
java.time.format.DateTimeParseException: Text 'NaN-aN-aN' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1951)
	at java.base/java.time.LocalDate.parse(LocalDate.java:428)
	at java.base/java.time.LocalDate.parse(LocalDate.java:413)
	at no.nav.helse.rapids_rivers.JsonMessageKt.asOptionalLocalDate(JsonMessage.kt:254)
	at no.nav.dagpenger.oppslag.soknadfakta.AvsluttedeArbeidsforholdLøsningServiceKt.getAvsluttedeArbeidsforhold(AvsluttedeArbeidsforholdLøsningService.kt:43)
	at no.nav.dagpenger.oppslag.soknadfakta.AvsluttedeArbeidsforholdLøsningService.makeLøsning$dp_oppslag_soknadfakta(AvsluttedeArbeidsforholdLøsningService.kt:23)
	at no.nav.dagpenger.oppslag.soknadfakta.SøknadsdataLøsningService.onPacket(SøknadsdataLøsningService.kt:44)
	at no.nav.helse.rapids_rivers.River.onPacket(River.kt:35)
	at no.nav.helse.rapids_rivers.River.onMessage(River.kt:28)
	at no.nav.helse.rapids_rivers.RapidApplication.onMessage(RapidApplication.kt:33)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecord(KafkaRapid.kt:100)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecords(KafkaRapid.kt:94)
	at no.nav.helse.rapids_rivers.KafkaRapid.consumeMessages(KafkaRapid.kt:109)
	at no.nav.helse.rapids_rivers.KafkaRapid.start(KafkaRapid.kt:63)
	at no.nav.helse.rapids_rivers.RapidApplication.start(RapidApplication.kt:38)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt:25)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt)
```

**Comment by geiralund** [comment]
feil ved henting av søknadsfakta (AvsluttedeArbeidsforhold): null 
stacktrace
```
java.lang.NullPointerException: null
	at no.nav.dagpenger.oppslag.soknadfakta.AvsluttedeArbeidsforholdLøsningServiceKt.getAvsluttedeArbeidsforhold(AvsluttedeArbeidsforholdLøsningService.kt:37)
	at no.nav.dagpenger.oppslag.soknadfakta.AvsluttedeArbeidsforholdLøsningService.makeLøsning$dp_oppslag_soknadfakta(AvsluttedeArbeidsforholdLøsningService.kt:23)
	at no.nav.dagpenger.oppslag.soknadfakta.SøknadsdataLøsningService.onPacket(SøknadsdataLøsningService.kt:44)
	at no.nav.helse.rapids_rivers.River.onPacket(River.kt:35)
	at no.nav.helse.rapids_rivers.River.onMessage(River.kt:28)
	at no.nav.helse.rapids_rivers.RapidApplication.onMessage(RapidApplication.kt:33)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecord(KafkaRapid.kt:100)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecords(KafkaRapid.kt:94)
	at no.nav.helse.rapids_rivers.KafkaRapid.consumeMessages(KafkaRapid.kt:109)
	at no.nav.helse.rapids_rivers.KafkaRapid.start(KafkaRapid.kt:63)
	at no.nav.helse.rapids_rivers.RapidApplication.start(RapidApplication.kt:38)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt:25)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt)
```
