### ISSUE TITLE
Feil i dp-oppslag-fakta : java.util.NoSuchElementException: List is empty.

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#651]
Stacktrace: 

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
	at no.nav.dagpenger.oppslag.soknadfakta.LøsningService.arbeidspliktEllerLønnsplikt(LøsningService.kt:86)
	at no.nav.dagpenger.oppslag.soknadfakta.LøsningService.onPacket(LøsningService.kt:62)
	at no.nav.helse.rapids_rivers.River.onPacket(River.kt:35)
	at no.nav.helse.rapids_rivers.River.onMessage(River.kt:28)
	at no.nav.helse.rapids_rivers.RapidApplication.onMessage(RapidApplication.kt:33)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecord(KafkaRapid.kt:100)
	at no.nav.helse.rapids_rivers.KafkaRapid.onRecords(KafkaRapid.kt:94)
	at no.nav.helse.rapids_rivers.KafkaRapid.consumeMessages(KafkaRapid.kt:109)
	at no.nav.helse.rapids_rivers.KafkaRapid.start(KafkaRapid.kt:63)
	at no.nav.helse.rapids_rivers.RapidApplication.start(RapidApplication.kt:38)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt:18)
	at no.nav.dagpenger.oppslag.soknadfakta.ApplicationKt.main(Application.kt)
```

- [ ] Tester for lesing av søknadsdata

**Comment by geiralund** [comment]
Vi må legge til tester!
